@startuml
'https://plantuml.com/activity-diagram-beta

start
partition Initialization {

:Game.Program.Engine.Create;
:Read Settings Json;
:Register Services;
split
    partition WindowService.CreateWindow{
        :InitWindow;
        :SetTargetFPS;
        :SetFullScreen;
        :SetRenderQueue;
        :SetTempCamera;
    }
    
split again
    partition SceneService.Start{
        partition SceneService.LoadScene{
            partition SceneService.Read{
                :ReadSceneJson;
                :ConvertDataTypes;
                :Return Scene;
            }
            :SaveSceneToLoadedScenes;
            :AddObjectsToRenderQueue;
            :SetCamera;
        }
    }
    
split again
    partition ScriptService.Start{
        :GetScripts;
        :InitScripts;
        :SendData;
        :WriteReturnedDataToEngine;
    }
end split   
}
partition Running{
    while (!WindowShouldClose)
        split
            partition ScriptService.Update{
                :SendData;
                :WriteReturnedDataToEngine;
            }
        split again
            :WindowService.Draw;
        end split   
    endwhile
}  
    
    
end

@enduml
