@startuml
'https://plantuml.com/activity-diagram-beta

start
partition Initialization {

:Game.Program.Engine.Create;
:Read Settings Json;
:Register Services;
fork
    partition WindowService.CreateWindow{
        :InitWindow;
        :SetTargetFPS;
        :SetFullScreen;
        :SetRenderQueue;
        :SetTempCamera;
    }
    
fork again
    partition SceneService.Start{
        :ReadSceneJson;
        :ConvertDataTypes;
        :Return Scene;
        :SaveSceneToLoadedScenes;
        :AddObjectsToRenderQueue;
        :SetCamera;
    }
    
fork again
    partition ScriptService.Start{
        :GetScripts;
        :InitScripts;
        :SendData;
        :WriteReturnedDataToEngine;
    }
end fork   
}
partition Running{
    while (!WindowShouldClose)
        fork
            partition ScriptService.Update{
                :SendData;
                :WriteReturnedDataToEngine;
            }
        fork again
            :WindowService.Draw;
        end fork   
    endwhile
}  
    
    
end

@enduml
