@startuml Engine
start;
:Game.Program;
:Engine3D.Engine;
:Engine3D.Services.WindowService.CreateWindow();

:Engine3D.Services.SceneService.Start("SceneName");
:Engine3D.Services.ScriptService.Start();
while (!WindowShouldClose)
    :Engine3D.Services.WindowService.Update();
    :Engine3D.Services.ScriptService.Update();
    :Engine3D.Services.WindowService.Draw();
endwhile
end;
@enduml