@startjson
#highlight "Name"
{
    "Name":"PipelineName",
    "AssemblyMarker": "ClassNameOfChild",
    "ShaderFiles":[
        {
            "VertexShaderFile": "File.vert",
            "FragmentShaderFile": "File.frag"
        }
    ]
}
@endjson