@startjson
#highlight "Name"
{
    "RenderPipeline": {
        "Lights": null,
        "Name": "Lighting",
        "AssemblyMarker": "BasicLighting",
        "ShaderFile": {
          "VertexShaderFile": "base_lighting.vert",
          "FragmentShaderFile": "lighting.frag"
        }
      }
}
@endjson